### PR TITLE
Failing tests don't exit with 0 anymore

### LINKED ISSUE #43: Travis is passing builds when it shouldn't
Travis exits with code 0 even when the tests fail.

https://travis-ci.org/datasciencebr/rosie/jobs/228188652

image

### PR DESCRIPTION
**Pull request by cuducos**
Fix #43 — many thanks @cotsog!

### CODE REVIEW

**Comment by cuducos** [comment]
BTW if we were having failing tests this PR actually should be red… let's see…

**Comment by cuducos** [comment]
Ok. We don't have failures. I'm explicitly add `sys.exit(1)` to be sure we don't end up with `0`.

**Comment by Irio** [comment]
Shouldn't we close this in favor of https://github.com/datasciencebr/rosie/pull/47?

**Comment by cuducos** [comment]
#47 is merged here already.

**Comment by anaschwendler** [comment]
Hi @cuducos, I think that this PR is good to merge, no?
Can we make it in favor of #43 ?

**Comment by cuducos** [comment]
As I said before #47 is already merged into this branch. We merge this and both branches get merged into master. I'm just waiting a good soul to do the merge ; )

**Pull request merged**
