### PR TITLE
Remove side effects from traveled speeds classifier

### PR DESCRIPTION
**Pull request by MarcosX**
Looking at https://github.com/datasciencebr/rosie/issues/50 I decided to do a small refactoring on `traveled_speeds_classifier.py` and get feedback from maintainers to see if it's a good idea.

**Please notice that I have little experience with Python and very limited knowledge around the libs being used, feel free to call out any issues you see :)**

The biggest issue I noticed was the amount of side effects (mostly reassigning params and temp vars), so I decided to tackle that first.

Most of the refactorings I did were [split temp var](https://refactoring.com/catalog/splitTemporaryVariable.html), [replace temp var with query method](https://refactoring.com/catalog/replaceTempWithQuery.html) and [inline temp var](https://refactoring.com/catalog/inlineTemp.html).

All unit tests are running fine, but I'm not super confident that this is enough, so double check the logic to see if it makes sense and work as expected.

Let me know what you think and I can open other PRs with similar changes to other classifiers.

### CODE REVIEW

**Comment by anaschwendler** [comment]
Hey @MarcosX thanks you for that refactor!
I have an idea on how to test if everythings works, but I have found some errors along the way, can you help me in adjusting that?

What I did to test this PR:

1. Clone the project
```console
$ git clone git@github.com:datasciencebr/rosie.git
```
2. Get into folder
```console
$ cd rosie
```

3. Build the project 
```console
$ ./setup
```
4. Run the project with the master script
```console
$ python rosie.py run chamber_of_deputies
```

5. Checkout to @MarcosX PR:
```console
$ git checkout -b MarcosX-master master
```

5. Run the project with the @MarcosX PR:
```console
$ python rosie.py run chamber_of_deputies
```

But I got an error running this refactored script:
image

Here is what I did to get this error, @MarcosX did you get this same error?

My idea to test is:
6. Compare both `suspicions.xz` files generated with the scripts, loading both scripts and run `pandas.testing.assert_frame_equal` to see if they are equal ;)

If there is something that I can help, please drop a line!

**Comment by MarcosX** [comment]
Thanks @anaschwendler I'll check it out and will get back to you!

**Comment by MarcosX** [comment]
Hey @anaschwendler just to let you that now I got the same errors you mentioned. The problem was that I was using the dockerfile to run the tests but it was setup to use version python 3.5, after upgrading the image to run on python 3.6 I got the same errors :)

Since I did a few changes already it's hard for me to understand what went wrong (I'm still learning python :p), so I'll try to redo all changes and running tests after each one. Once it's all working I'll update this PR.

Thanks a lot for the help!

**Comment by anaschwendler** [comment]
Hi @MarcosX if you want to keep trying I suggest you to open a new PR with few modifications where we can test together the changes :)

I think that its better to learn more about python and receive more feedback, so if you want to create a new PR with [WIP] that means that is a work in progress, so we can help you to learn more!

**Comment by MarcosX** [comment]
Yep, I plan on doing that, just need to find the time :) Thanks!

**Pull request closed without merging**
