### PR TITLE
Generate a smaller docker image

### PR DESCRIPTION
**Pull request by caduvieira**
This is just a template to help you make your point clear with this PR. :)

**What is the purpose of this Pull Request?**
Generate a smaller docker image. From 1.38GB to 707 M
Change from CMD to Entrypoint. The command should be 
docker run --rm -v /tmp/serenata-data:/tmp/serenata-data rosie <module_name>

**What was done to achieve this purpose?**
Lesser layers and purging not needed packages

**How to test if it really works?**
docker build . -t rosie
docker run --rm -v /tmp/serenata-data:/tmp/serenata-data rosie test

**Who can help reviewing it?**
Anyone with docker :)

**TODO**
I tried using alpine image but the libs need for scikit-learn and scipy are not readily available in apline (FFTW, SLIB for example)

### CODE REVIEW

**Comment by cuducos** [comment]
Many thanks, @caduvieira — would mind updating the docs too in this PR? In the `CONTRIBUTING.md` we should have always the recommend way to run stuff — and this PR will then fix #65 ; )

**Comment by lipemorais** [comment]
Hey, @caduvieira! I tried to run `docker run --rm -v /tmp/serenata-data:/tmp/serenata-data rosie <module_name>` but the output was 
```
(.rosie-env) ➜  rosie git:(master) ✗ docker run --rm -v /tmp/serenata-data:/tmp/serenata-data rosie federal_senate
Usage:
  python rosie.py run chamber_of_deputies [<path to output directory>]
Testing:
  python rosie.py test
  python rosie.py test chamber_of_deputies
```

So I runned as `(.rosie-env) ➜  rosie git:(master) ✗ docker run --rm -v /tmp/serenata-data:/tmp/serenata-data rosie run federal_senate`

And look that it works but there is no logs, so I runned outside of Docker  and there is no log too.

I believe that the entry point needs: `ENTRYPOINT ["python", "rosie.py", "run"]` to have the behaviour that you proposed with `docker run --rm -v /tmp/serenata-data:/tmp/serenata-data rosie <module_name>`

**Comment by cuducos** [comment]
> I believe that the entry point needs: `ENTRYPOINT ["python", "rosie.py", "run"]`

I think that way the command to run tests will diverge… I prefer the way @caduvieira suggested, it's just a matter of using `<command and args>` instead of `<module name>` in the docs. Thus we have a Docker interface very similar to the CLI interface:

```
$ docker run --rm -v /tmp/serenata-data:/tmp/serenata-data rosie test
$ docker run --rm -v /tmp/serenata-data:/tmp/serenata-data rosie run <module_name>
```

**Comment by caduvieira** [comment]
Hope that fixes it

**Comment by lipemorais** [comment]
> I think that way the command to run tests will diverge… I prefer the way @caduvieira suggested, it's just a matter of using <command and args> instead of <module name> in the docs. Thus we have a Docker interface very similar to the CLI interface:

I completely agree. :)

**Comment by lipemorais** [comment]
Hey @caduvieira, just a small doubt.

I usually use `bash` or `sh` substituting a image CMD to debug a docker image.

How do you debug with a `ENTRYPOINT` changed? Do you overwrite it on ` docker run`?

**Comment by caduvieira** [comment]
You can use --entrypoint

> You can override the ENTRYPOINT instruction
> using the docker run --entrypoint flag.

From: https://docs.docker.com/engine/reference/builder/#entrypoint

**Comment by caduvieira** [comment]
Can anyone rerun this build? I think it failed because of the connection.

https://travis-ci.org/datasciencebr/rosie/builds/290710310#L571

**Comment by cuducos** [comment]
Sure thing @caduvieira, just restarted— about the error this is indeed something undesired in our tests suite, [it was supposed to be temporary, but… it still there months and months later](https://github.com/datasciencebr/rosie/pull/59#pullrequestreview-45154031)…

**Comment by anaschwendler** [comment]
Hey @caduvieira we finally fixed the problem with the Travis yesterday, I've run the tests again and now is working again, do you mind updating your branch?

Thanks! :)

**Comment by caduvieira** [comment]
> Hey @caduvieira we finally fixed the problem with the Travis yesterday, I've run the tests again and now is working again, do you mind updating your branch?

Done rebase.

**Comment by anaschwendler** [comment]
Thanks @caduvieira, for me now we are done :)

What I did to full test this PR:

1. Clone the project:
```console
$ git clone git@github.com:datasciencebr/rosie.git
```

2. Change to Rosie' folder:
```console
$ cd rosie
```

3. Change to the tested branch:
```console
$ git checkout -b caduvieira-master master
```

4. Merge its content:
```console
$ git pull https://github.com/caduvieira/rosie.git master
```

5. Run the new Docker commands:
```console
$ docker build -t rosie .
$ docker run --rm -v /tmp/serenata-data:/tmp/serenata-data rosie test
```

The result:
```console
➜  rosie git:(caduvieira-master) docker run --rm -v /tmp/serenata-data:/tmp/serenata-data rosie test
......................................................................
----------------------------------------------------------------------
Ran 70 tests in 4.046s

OK
```

I'll run the `chamber_of_deputies` and `federal_senate` to be sure, but great work !

**Pull request merged**
