### PR TITLE
Adds undocumented types to convert to None

### LINKED ISSUE #72: New bug while renaming categories
As reported by @cuducos on #71 there's a bug when renaming the categories. I ran the code on master to check, it is there too, and [here is the traceback when running on master](https://gist.github.com/jtemporal/e071f71ab6e282bcce369d366aa4e935)

### PR DESCRIPTION
**Pull request by jtemporal**
This should fix #72

### CODE REVIEW

**Comment by cuducos** [comment]
If the only allowed values are `0`, `1` and `2` I think `converters` should return `None` to anything else — and not only to `3`, `4` and `5`.

What about this implementation of `converters`?

```python
>>> from collections import defaultdict
>>> converters = defaultdict(lambda: None)
>>> for i in range(3):
...     converters[i] = i
...
>>> print(converters[0])
0
>>> print(converters[1])
1
>>> print(converters[2])
2
>>> print(converters[3])
None
>>> print(converters[4])
None
>>> print(converters[5])
None
>>> print(converters[42])
None
```

**Comment by jtemporal** [comment]
>What about this implementation of `converters`?

Very classy @cuducos! Implemented in fa719dc ;)

**Comment by cuducos** [comment]
> Very classy @cuducos! Implemented in `fa719dc` ;)

Pandas doesn't think so:

```
raise ValueError("new categories need to have the same number of "
ValueError: new categories need to have the same number of items than the old categories!
```

Not sure if related to the PR but this was the error message we had before, right?

**Comment by jtemporal** [comment]
>Not sure if related to the PR but this was the error message we had before, right?

I don't recall that happening before.

**Pull request merged**
